In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from pydataset import data

In [2]:
# 4. Acquisition/details about 'iris'
df_iris = data('iris')

In [3]:
print(df_iris.head(3))

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa


In [5]:
print(df_iris.shape)

(150, 5)


In [6]:
print(df_iris.columns)

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')


In [9]:
print(df_iris.dtypes)

Sepal.Length    float64
Sepal.Width     float64
Petal.Length    float64
Petal.Width     float64
Species          object
dtype: object


In [10]:
print(df_iris.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 7.0+ KB
None


In [11]:
print(df_iris.describe())

       Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


In [13]:
# 5. Read the Table1_CustDetails table from your spreadsheet execises google sheet into a dataframe named 
# df_google_sheets
custdet_sheet_url = 'https://docs.google.com/spreadsheets/d/1R2r3u9ZITI7yGZRzMBzBy_u8J-MXIwRSOsZdEoJO5nE/edit#gid=1023018493'
csv_export_url = custdet_sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')
df_google_sheets = pd.read_csv(csv_export_url)
df_google_sheets.head()

customer_id  gender  is_senior_citizen partner dependents  phone_service  \
0  0002-ORFBO  Female                  0     Yes        Yes              1   
1  0003-MKNFE    Male                  0      No         No              2   
2  0004-TLHLJ    Male                  0      No         No              1   
3  0011-IGKFF    Male                  1     Yes         No              1   
4  0013-EXCHZ  Female                  1     Yes         No              1   

   internet_service  contract_type      payment_type  monthly_charges  \
0                 1              1      Mailed check             65.6   
1                 1              0      Mailed check             59.9   
2                 2              0  Electronic check             73.9   
3                 2              0  Electronic check             98.0   
4                 2              0      Mailed check             83.9   

   total_charges churn  
0         593.30    No  
1         542.40    No  
2         280.85   Yes  
3        1237.85   Yes  
4         267.40   Yes

In [14]:
df_google_sheets_sample = df_google_sheets.iloc[:100]

In [18]:
print(df_google_sheets.shape[0])

7049


In [23]:
print(df_google_sheets_sample.iloc[:0, :5])

Empty DataFrame
Columns: [customer_id, gender, is_senior_citizen, partner, dependents]
Index: []


In [26]:
print(df_google_sheets_sample.select_dtypes(include='object').iloc[:0, :])

Empty DataFrame
Columns: [customer_id, gender, partner, dependents, payment_type, churn]
Index: []


In [36]:
column_n = list(df_google_sheets_sample.select_dtypes(include='number'))

In [55]:
for i in column_n:
    range = df_google_sheets[i].max() - df_google_sheets[i].min()
    print(f'Column: {i}, Range: {range}')
    
df_google_sheets.select_dtypes('number').apply(lambda col: col.max() - col.min()).rename('range')

Column: is_senior_citizen, Range: 1
Column: phone_service, Range: 2
Column: internet_service, Range: 2
Column: contract_type, Range: 2
Column: monthly_charges, Range: 100.5
Column: total_charges, Range: 8666.0


is_senior_citizen       1.0
phone_service           2.0
internet_service        2.0
contract_type           2.0
monthly_charges       100.5
total_charges        8666.0
Name: range, dtype: float64

In [43]:
# 6. Download your spreadsheet exercises google sheet as an excel file, read the Table1_CustDetails worksheet into a 
# df named df_excel
df_excel = pd.read_excel('Spreadsheet_Waterman.xlsx')

In [45]:
df_excel_sample = df_excel.head(100)

In [47]:
df_excel.shape[0]

7049

In [48]:
print(df_excel.iloc[:0, :5])

Empty DataFrame
Columns: [customer_id, gender, is_senior_citizen, partner, dependents]
Index: []


In [50]:
df_excel.dtypes

customer_id           object
gender                object
is_senior_citizen    float64
partner               object
dependents            object
phone_service        float64
internet_service     float64
contract_type        float64
payment_type          object
monthly_charges      float64
total_charges        float64
churn                 object
dtype: object

In [52]:
df_excel.describe()

is_senior_citizen  phone_service  internet_service  contract_type  \
count        7049.000000    7049.000000       7049.000000    7049.000000   
mean            0.162009       1.324585          1.222585       0.690878   
std             0.368485       0.642709          0.779068       0.833757   
min             0.000000       0.000000          0.000000       0.000000   
25%             0.000000       1.000000          1.000000       0.000000   
50%             0.000000       1.000000          1.000000       0.000000   
75%             0.000000       2.000000          2.000000       1.000000   
max             1.000000       2.000000          2.000000       2.000000   

       monthly_charges  total_charges  
count      7049.000000    7038.000000  
mean         64.747014    2283.043883  
std          30.099460    2266.521984  
min          18.250000      18.800000  
25%          35.450000     401.587500  
50%          70.350000    1397.100000  
75%          89.850000    3793.775000  
max         118.750000    8684.800000

In [53]:
print(df_excel.select_dtypes(include='object').iloc[:0, :])

Empty DataFrame
Columns: [customer_id, gender, partner, dependents, payment_type, churn]
Index: []


In [54]:
df_excel.select_dtypes('number').apply(lambda col: col.max() - col.min()).rename('range')

is_senior_citizen       1.0
phone_service           2.0
internet_service        2.0
contract_type           2.0
monthly_charges       100.5
total_charges        8666.0
Name: range, dtype: float64

In [56]:
# 7. Read the data from (provided) google sheet into a dataframe, df_google
train_sheet_url = 'https://docs.google.com/spreadsheets/d/1Uhtml8KY19LILuZsrDtlsHHDC9wuDGUSe8LTEwvdI5g/edit#gid=341089357'
train_sheet_url_mod = train_sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')
df_google = pd.read_csv(train_sheet_url_mod)

In [57]:
print(df_google.head(3))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  


In [58]:
print(df_google.shape)

(891, 12)


In [60]:
print(df_google.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [63]:
print(df_google.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object


In [64]:
print(df_google.describe())

       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200  


In [66]:
df_google.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [78]:
for col in df_google:
    if col in ['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked']:
        print(df_google[col].unique())

[0 1]
[3 1 2]
['male' 'female']
[1 0 3 4 2 5 8]
[0 1 2 5 3 4 6]
['S' 'C' 'Q' nan]


In [79]:
df_google.select_dtypes('object').apply(lambda col: col.unique().tolist())

Name        [Braund, Mr. Owen Harris, Cumings, Mrs. John Bradley (Florence Briggs Thayer), Heikkin...
Sex                                                                                    [male, female]
Ticket      [A/5 21171, PC 17599, STON/O2. 3101282, 113803, 373450, 330877, 17463, 349909, 347742,...
Cabin       [nan, C85, C123, E46, G6, C103, D56, A6, C23 C25 C27, B78, D33, B30, C52, B28, C83, F3...
Embarked                                                                               [S, C, Q, nan]
dtype: object